### PR TITLE
v3.3.0 Update, Make Improvement to Trigger Setting Page

### PR DESCRIPTION
**Pull request by chanx**
Hello, i'm fork midi-relay, and make some update to fit my requirement to use this MIDI-relay to forward command from ProPresenter Macro to Bitfocus Companion.

Here is some major improvement:
1. Add Context Menu to Open Triggers Settings page, so I can easily update and see the triggers setting
2. Fix Edit Triggers not populate the record to the Edit Form
3. Add some cosmetic css and functionality to Triggers Setting Page
4. Add some helpers info for calling Bitfocus Companion Http API, make it easier to add/edit Triggers
5. Because I'm using Windows and i need to build dist so I add scripts to package.json to electron-builder --windows

Full change can see in the change. 

Hope you can check and review this pull.

Thanks.

### CODE REVIEW

**Comment by chanx** [comment]
This will fix this bug
https://github.com/josephdadams/midi-relay/issues/47

**Comment by josephdadams** [comment]
Great work!

**Comment by chanx** [comment]
Thank you... No new release yet?

**Comment by josephdadams** [comment]
I will create one today

**Pull request merged**
